### ISSUE TITLE
register cloud service for the Docker images

### ISSUE THREAD

**Issue by jurgenvinju** [crossminer/crossminer#10] opened 2017-09-29 14:13 UTC

**Comment by borisbaldassari** [comment] 2017-11-10 16:07
Done on [codefresh](https://codefresh.io). Might switch to another provider if some feature is missing or..
Also setup an integration with the # ci slack channel.

**Comment by borisbaldassari** [comment] 2017-11-10 16:08
I also registered the [crossminer organisation](https://hub.docker.com/u/crossminer/) on dockerhub.

**Comment by tdegueul** [comment] 2017-11-13 14:26
Hi @borisbaldassari, thanks for the hard work!

I tried to make it work locally:

```
[ start a local MongoDB, just in case ]
$ sudo docker pull crossminer/ossmeter-platform
$ sudo docker run crossminer/ossmeter-platform
Starting Admin bundle
INFO  [OssmeterApplication] (14:23:32): Application initialising.
Unable to init server: Could not connect: Connection refused
Eclipse:
An error has occurred. See the log file
/ossmeter/configuration/1510583011771.log.
```

I'm not fluent in Docker yet so I don't really know how to check the logfile to verify which server refuses connection :(

if you cannot think of an easy fix, I'll dive into it to see what's going on. Please let me know.

**Comment by MarcioMateus** [comment] 2017-11-13 14:38
Hi @tdegueul, the docker images were created to run as a distributed application, being launched from the docker-compose file. They probably need some changes for them to work in other setups. If I understood correctly, you intend to only run this specific image with a local instance of the MongoDB, right?

**Comment by tdegueul** [comment] 2017-11-13 14:47
I was eager to test so I just missed the docker-compose part. Eh, my bad.

I can confirm everything's working here. Platform/API/WebApp. Great job!

**Comment by borisbaldassari** [comment] 2017-11-13 15:32
Marcio seems to be just too reactive for me.. Thanks Marcio for the lightening-fast support! :-D

**Comment by borisbaldassari** [comment] 2017-12-26 09:52
Closing issue since the service seems to work.

**Closed as completed by borisbaldassari** 2017-12-26 09:52 UTC
